- name: Create Pull Request
id: cpr
uses: peter-evans/create-pull-request@v3
- name: Check outputs
if: ${{ steps.cpr.outputs.pull-request-number }}
run: |
  echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
  echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
